#!/usr/bin/env bash
PROGRAM="$1"
OPT="-l"

cd learning/ls_dirs || exit

echo "single file"
valgrind -q "${PROGRAM}" "$OPT" a

echo -e "\nmultiple file"
valgrind -q "${PROGRAM}" "$OPT" a b c

echo -e "\nmultiple file + error"
valgrind -q "${PROGRAM}" "$OPT" c b a f1 f3 f2

echo -e "\nempty"
valgrind -q "${PROGRAM}" "$OPT"

echo -e "\nsingle dir"
valgrind -q "${PROGRAM}" "$OPT" x

echo -e "\nmultiple dir"
valgrind -q "${PROGRAM}" "$OPT" z x z

echo -e "\nmultiple dir + error"
valgrind -q "${PROGRAM}" "$OPT" z x y z

echo -e "\nmultiple file + multiple dir + error"
valgrind -q "${PROGRAM}" "$OPT" x b a f2 f1 x y z y f3

echo -e "\nmissing folder"
valgrind -q "${PROGRAM}" "$OPT" d1/f4

echo -e "\nmissing folder and multiforlder"
valgrind -q "${PROGRAM}" "$OPT" d1/f4 x x
